// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDocsDemo.NET.Data;

namespace RDocsDemo.NET.Migrations
{
    [DbContext(typeof(RDocsDemoNETContext))]
    [Migration("20191031235157_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RDocsDemo.NET.Models.Document", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contents");

                    b.Property<string>("Filename");

                    b.Property<DateTime>("IssueDate");

                    b.Property<DateTime>("LoadDate");

                    b.Property<string>("NamedParts");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
